coverage:
    status:
        project:
            default:
                target: auto
                threshold: 1%
                base: auto
        patch:
            default:
                target: auto
                threshold: 1%

comment:
    layout: "header, diff, flags, components"
    behavior: default
    require_changes: false

ignore:
    - "tests/**/*"
    - "examples/**/*"
    - "scripts/**/*"
